#!/usr/bin/env bash

git -C `dirname "$0"` submodule update --init Tools/khamake
git -C `dirname "$0"` submodule update --init Backends/Kore-hxcpp/khacpp

. `dirname "$0"`/Tools/platform.sh
git -C `dirname "$0"` submodule update --depth 1 --init "Tools/$KORE_PLATFORM"

git -C `dirname "$0"` submodule update --init Kore
bash `dirname "$0"`/Kore/get_dlc
