name: iOS (Metal)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get DLC
      run: ./get_dlc
    - name: Get Node.js
      run: git clone https://github.com/Kode/nodejs_bin.git --depth 1
    - name: Setup Node.js
      run: nodejs_bin/copysysbin.sh
    - name: Compile
      run: nodejs_bin/node make.js ios -g metal --kha . --from Tests/Empty --nosigning --compile
